version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: twitifynd
      POSTGRES_PASSWORD: twitter
    ports:
      - 5432:5432
  mail:
    image: bytemark/smtp
    restart: always
    ports:
      - 25:25
  twitifynd:
    build: .
    environment:
      POSTGRES_DB: twitifynd
      POSTGRES_USER: postgres
      PGPASSWORD: twitter
      SPOTIFY_ID: ${SPOTIFY_ID}
      SPOTIFY_SECRET: ${SPOTIFY_SECRET}
      TWITTER_BEARER: ${TWITTER_BEARER}
      RECEIVER_EMAIL: ${RECEIVER_EMAIL}
      ALERT_LEVEL: 1
      SKIP_ARTIST_RESULT: 0
      # ALERT_LEVEL: 1-minimal, warnings only; 2-startup and other events; 3-verbose
    volumes:
      - script_logs:/data/script_logs
      - script_data:/data/script_data
      - script_counters:/data/script_counters
      # TODO: specify restart on crash
volumes:
  script_logs: {}
  script_data: {}
  script_counters: {}